name: Deploy to test

on:
  push:
    branches:
      - develop

concurrency: deploy-test

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: test

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          EARTHDATA_USERNAME: ${{ secrets.EARTHDATA_USERNAME }}
          EARTHDATA_PASSWORD: ${{ secrets.EARTHDATA_PASSWORD }}
          INGEST_TOPIC_ARN: ${{ secrets.INGEST_TOPIC_ARN }}
          HYP3_ACCOUNT_IDS: ${{ secrets.HYP3_ACCOUNT_IDS }}
          CMR_DOMAIN: cmr.uat.earthdata.nasa.gov
          HYP3_CONTENT_BUCKET: hyp3-opera-uat-contentbucket-hnb0kgwnsc0b
          TEMPLATE_BUCKET: cf-templates-118ylv0o6jp2n-us-west-2
          APP_STACK_NAME: ingest-adapter-test
