name: Deploy to prod

on:
  push:
    branches:
      - main

concurrency: deploy-prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: prod

    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deploy
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          EARTHDATA_USERNAME: ${{ secrets.EARTHDATA_USERNAME }}
          EARTHDATA_PASSWORD: ${{ secrets.EARTHDATA_PASSWORD }}
          INGEST_TOPIC_ARN: ${{ secrets.INGEST_TOPIC_ARN }}
          QUEUE_URL: ${{ secrets.QUEUE_URL }}
          HYP3_ACCOUNT_IDS: ${{ secrets.HYP3_ACCOUNT_IDS }}
          CMR_DOMAIN: cmr.earthdata.nasa.gov
          HYP3_CONTENT_BUCKET: hyp3-opera-prod-contentbucket-2ypbtzzskwyr
          TEMPLATE_BUCKET: cf-templates-118mtzosmrltk-us-west-2
          APP_STACK_NAME: ingest-adapter-prod
