name: Create release and sync to default branch

on:
  push:
    tags:
      - v*

jobs:
  create-release:
    uses: ASFHyP3/actions/.github/workflows/reusable-release.yml@v0.18.0
    with:
      release_prefix: Ingest Adapter
    secrets:
      USER_TOKEN: ${{ secrets.TOOLS_BOT_PAK }}
