name: Static analysis

on: push

jobs:
  call-secrets-analysis-workflow:
    # Docs: https://github.com/ASFHyP3/actions
    uses: ASFHyP3/actions/.github/workflows/reusable-secrets-analysis.yml@v0.18.1

  call-ruff-workflow:
    # Docs: https://github.com/ASFHyP3/actions
    uses: ASFHyP3/actions/.github/workflows/reusable-ruff.yml@v0.18.1

  call-mypy-workflow:
    # Docs: https://github.com/ASFHyP3/actions
    uses: ASFHyP3/actions/.github/workflows/reusable-mypy.yml@v0.18.1

  cfn-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml

      - shell: bash -l {0}
        run: |
          cfn-lint --info --ignore-checks W3002 --template app/cloudformation.yml
