name: Tag release version

on:
  push:
    branches:
      - main

jobs:
  create-tag:
    uses: ASFHyP3/actions/.github/workflows/reusable-bump-version.yml@v0.18.1
    secrets:
      USER_TOKEN: ${{ secrets.TOOLS_BOT_PAK }}
